#!/bin/bash

rm -f list-$1.txt
for ((i=1;i<=10;i++)) do
echo "www.imdb.com/search/title?genres=$1&title_type=feature&sort=moviemeter,asc&page=$i"
wget "www.imdb.com/search/title?genres=$1&title_type=feature&sort=moviemeter,asc&page=$i" -O temp.html
cat temp.html | grep adv_li_i | sed 's?/tt? tt?g' | sed 's|/?| |g' | awk '{print $3}' >> list-$1.txt
done
rm -f temp.html
