#!/bin/bash

for var1 in `head -100 list-$1.txt`
do
wget http://www.imdb.com/title/$var1 -O temp
wget `cat temp | grep tt_pv_vi_aiv_1 | sed 's/<a href="/www.imdb.com/g' | cut -d'?' -f1` -O $var1-video
wget `cat $var1-video  | tr '{}' '\n' | grep mp4 | sort | uniq | sed 's/"definition":"//g' | sed 's/p","/ /g' | sort -n -r | tr '"' ' ' | awk '{print $NF}' | head -1` -O $var1-video.mp4 

sec_tot=`ffprobe -v error -show_entries format=duration \-of default=noprint_wrappers=1:nokey=1 $var1-video.mp4`
nframe=10
frdaeliminare=11

framerate=$nframe/$sec_tot

ffmpeg -i $var1-video.mp4 -y -vf fps=$framerate -s 720x480 -aspect 1.5 -b:v 2000  $2$1-$var1-video-frame-%d.png
rm -f $2$1-$var1-video-frame-$frdaeliminare.png
montage $2$1-$var1-video-frame-*.png -geometry 720x480 -tile 10x1 $2$var1-tile.png
ALTEZZA=`convert $2$var1-tile.png -fuzz 10% -trim -print "%h" out.png;`
let "taglio = (480 - $ALTEZZA) / 2 "
convert $2$var1-tile.png -crop 7200x$ALTEZZA+0+$taglio -gravity center $2$var1-tile.png
convert $2$var1-tile.png -crop 720x480 $2$1-$var1-video-frame-%d.png
mv $2$1-$var1-video-frame-0.png $2$1-$var1-video-frame-10.png

rm -f out.png
rm -f $var1-video
rm -f $var1-video.mp4
rm -f $2$var1-tile.png
done

rm -f temp
